export const AUCTION_CATEGORIES = [
  "Barang Antik",
  "Seni Kontemporer",
  "Kendaraan Klasik",
  "Supercar & Hypercar",
  "Properti Mewah",
  "Jam Tangan Eksklusif",
  "Perhiasan & Permata",
  "Gadget & Teknologi Terkini",
  "Sneaker Hype & Streetwear",
  "Koin Langka & Numismatik",
  "Relik & Pedang Kerajaan",
  "Armor & Baju Besi Kuno",
  "Tas Desainer & Fashion Elite",
  "Memorabilia Olahraga",
  "Peralatan Gaming Edisi Terbatas",
  "Kartu Koleksi (Trading Cards)",
  "Karya Patung & Pahat",
  "Porselen Cina & Keramik",
  "Furnitur Era Victorian",
  "Buku Edisi Terbatas & Kuno",
  "Manuskrip Sejarah",
  "Permadani Kuno",
  "Alat Musik Klasik",
  "Mainan Retro & Vintage",
  "Prangko Langka",
  "Piringan Hitam (Vinyl)",
  "Kamera Analog & Lensa",
  "Koleksi Anggur (Fine Wine)",
  "Cerutu Premium (Cigars)",
  "Fosil & Spesimen Biologi",
  "Meteorit & Batu Luar Angkasa",
  "Kapal Pesiar (Yachts)",
  "Jet Pribadi",
  "Real Estate Komersial",
  "Domain Internet Premium",
  "NFT & Aset Digital Langka",
  "Memorabilia Perfilman",
  "Koleksi Militer Kuno",
  "Lukisan Renaisans",
  "Barang Lelang Sitaan Negara",
  "Tiket VVIP & Pengalaman Eksklusif",
  "Barang Koleksi Otomotif"
];
