const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const realisticAuctions = [
  // Barang Antik
  {
    title: "Vas Dinasti Ming Asli (Abad 15)",
    description: "Vas porselen asli peninggalan Dinasti Ming dengan motif naga biru yang sangat langka. Kondisi sempurna tanpa retak, dilengkapi sertifikat keaslian dari Museum Nasional.",
    category: "Barang Antik",
    rarity: "LEGENDARY",
    auctionType: "STANDARD",
    status: "ACTIVE",
    startingPrice: 250000,
    currentPrice: 300000,
    minimumIncrement: 10000,
    startTime: new Date(),
    endTime: new Date(Date.now() + 86400000 * 5),
    imageUrls: ["https://images.unsplash.com/photo-1596492348545-06a59b6572e9?w=800"],
  },
  {
    title: "Mesin Tik Vintage Underwood 1920",
    description: "Mesin tik klasik Underwood yang direstorasi penuh. Masih berfungsi dengan baik dan memiliki nilai sejarah tinggi bagi kolektor literatur.",
    category: "Barang Antik",
    rarity: "RARE",
    auctionType: "STANDARD",
    status: "ACTIVE",
    startingPrice: 15000,
    currentPrice: 20000,
    minimumIncrement: 1000,
    startTime: new Date(),
    endTime: new Date(Date.now() + 86400000 * 2),
    imageUrls: ["https://images.unsplash.com/photo-1522223832742-5ba0534c05cb?w=800"],
  },
  {
    title: "Kamera Leica IIIa 1935 Bawaan Asli",
    description: "Kamera Leica seri IIIa produksi tahun 1935 yang legendaris di kalangan fotografer klasik. Lensa Elmar 50mm f/3.5 dalam kondisi mulus.",
    category: "Barang Antik",
    rarity: "EPIC",
    auctionType: "STANDARD",
    status: "ACTIVE",
    startingPrice: 45000,
    currentPrice: 50000,
    minimumIncrement: 2500,
    startTime: new Date(),
    endTime: new Date(Date.now() + 86400000 * 3),
    imageUrls: ["https://images.unsplash.com/photo-1453230806017-56d81464b6c5?w=800"],
  },

  // Seni Kontemporer
  {
    title: "Lukisan 'Senja di Batavia' by Maestro",
    description: "Karya seni kontemporer minyak di atas kanvas. Menggambarkan suasana senja yang dramatis dengan perpaduan warna eksentrik.",
    category: "Seni Kontemporer",
    rarity: "EPIC",
    auctionType: "STANDARD",
    status: "ACTIVE",
    startingPrice: 75000,
    currentPrice: 80000,
    minimumIncrement: 5000,
    startTime: new Date(),
    endTime: new Date(Date.now() + 86400000 * 4),
    imageUrls: ["https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800"],
  },
  {
    title: "Patung Abstrak 'The Thinker 2.0'",
    description: "Patung tembaga modern yang melambangkan kerumitan pikiran manusia di era digital.",
    category: "Seni Kontemporer",
    rarity: "RARE",
    auctionType: "STANDARD",
    status: "ACTIVE",
    startingPrice: 40000,
    currentPrice: 40000,
    minimumIncrement: 2000,
    startTime: new Date(),
    endTime: new Date(Date.now() + 86400000 * 6),
    imageUrls: ["https://images.unsplash.com/photo-1544257121-826352cbb935?w=800"],
  },

  // Supercar & Hypercar
  {
    title: "Ferrari F40 Tahun 1989 (Rosso Corsa)",
    description: "Ikon supercar tahun 80-an dengan kondisi mesin terawat, odometer rendah (under 10k mil).",
    category: "Supercar & Hypercar",
    rarity: "LEGENDARY",
    auctionType: "STANDARD",
    status: "ACTIVE",
    startingPrice: 2500000,
    currentPrice: 2600000,
    minimumIncrement: 50000,
    startTime: new Date(),
    endTime: new Date(Date.now() + 86400000 * 7),
    imageUrls: ["https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800"],
  },
  {
    title: "Lamborghini Aventador SVJ Roadster",
    description: "Hanya diproduksi 800 unit di dunia. Warna khusus Verde Mantis. V12 naturally aspirated dengan raungan mematikan.",
    category: "Supercar & Hypercar",
    rarity: "LEGENDARY",
    auctionType: "STANDARD",
    status: "ACTIVE",
    startingPrice: 4500000,
    currentPrice: 4500000,
    minimumIncrement: 100000,
    startTime: new Date(),
    endTime: new Date(Date.now() + 86400000 * 10),
    imageUrls: ["https://images.unsplash.com/photo-1621007947382-bb3c3994e3fd?w=800"],
  },
  {
    title: "McLaren P1 Edisi Hitam Karbon",
    description: "Hypercar hybrid legendaris dari McLaren. Kombinasi serat karbon penuh.",
    category: "Supercar & Hypercar",
    rarity: "LEGENDARY",
    auctionType: "LIVE",
    status: "ACTIVE",
    startingPrice: 8000000,
    currentPrice: 8500000,
    minimumIncrement: 200000,
    startTime: new Date(),
    endTime: new Date(Date.now() + 86400000 * 2),
    imageUrls: ["https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800"],
  },

  // Jam Tangan Eksklusif
  {
    title: "Rolex Daytona 'Paul Newman' Ref 6239",
    description: "Jam tangan impian para kolektor. Dial eksotik dengan patina yang menawan.",
    category: "Jam Tangan Eksklusif",
    rarity: "LEGENDARY",
    auctionType: "STANDARD",
    status: "ACTIVE",
    startingPrice: 1200000,
    currentPrice: 1350000,
    minimumIncrement: 20000,
    startTime: new Date(),
    endTime: new Date(Date.now() + 86400000 * 3),
    imageUrls: ["https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=800"],
  },
  {
    title: "Patek Philippe Nautilus 5711/1A",
    description: "Kondisi brand new in box (BNIB). Dial biru yang sangat diburu di pasar global.",
    category: "Jam Tangan Eksklusif",
    rarity: "EPIC",
    auctionType: "STANDARD",
    status: "ACTIVE",
    startingPrice: 850000,
    currentPrice: 900000,
    minimumIncrement: 15000,
    startTime: new Date(),
    endTime: new Date(Date.now() + 86400000 * 4),
    imageUrls: ["https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800"],
  },

  // Properti Mewah
  {
    title: "Villa Sunset Bali di Uluwatu",
    description: "Villa dengan pemandangan langsung ke tebing Samudera Hindia. 5 Kamar Tidur, Infinity Pool.",
    category: "Properti Mewah",
    rarity: "LEGENDARY",
    auctionType: "STANDARD",
    status: "ACTIVE",
    startingPrice: 15000000,
    currentPrice: 15500000,
    minimumIncrement: 500000,
    startTime: new Date(),
    endTime: new Date(Date.now() + 86400000 * 14),
    imageUrls: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800"],
  },
  {
    title: "Penthouse Manhattan, NYC",
    description: "Penthouse super mewah dengan pemandangan 360 derajat Central Park.",
    category: "Properti Mewah",
    rarity: "LEGENDARY",
    auctionType: "STANDARD",
    status: "ACTIVE",
    startingPrice: 40000000,
    currentPrice: 40000000,
    minimumIncrement: 1000000,
    startTime: new Date(),
    endTime: new Date(Date.now() + 86400000 * 20),
    imageUrls: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800"],
  },

  // Perhiasan & Permata
  {
    title: "Cincin Berlian Pink Langka 5 Karat",
    description: "Berlian murni tanpa cacat dengan warna pink cerah yang sangat jarang ditemukan di alam liar.",
    category: "Perhiasan & Permata",
    rarity: "LEGENDARY",
    auctionType: "STANDARD",
    status: "ACTIVE",
    startingPrice: 2000000,
    currentPrice: 2100000,
    minimumIncrement: 50000,
    startTime: new Date(),
    endTime: new Date(Date.now() + 86400000 * 5),
    imageUrls: ["https://images.unsplash.com/photo-1605100804763-247f67b2548e?w=800"],
  },
  {
    title: "Kalung Zamrud (Emerald) Kolombia",
    description: "Batu zamrud hijau pekat seberat 12 karat yang dikelilingi berlian 18k white gold.",
    category: "Perhiasan & Permata",
    rarity: "EPIC",
    auctionType: "STANDARD",
    status: "ACTIVE",
    startingPrice: 400000,
    currentPrice: 400000,
    minimumIncrement: 10000,
    startTime: new Date(),
    endTime: new Date(Date.now() + 86400000 * 6),
    imageUrls: ["https://images.unsplash.com/photo-1599643478524-fb66f7f21223?w=800"],
  },

  // Sneaker Hype & Streetwear
  {
    title: "Air Jordan 1 x Dior High (Size 42)",
    description: "Kolaborasi super hype yang dirilis terbatas. BNIB dengan aksesori lengkap.",
    category: "Sneaker Hype & Streetwear",
    rarity: "LEGENDARY",
    auctionType: "STANDARD",
    status: "ACTIVE",
    startingPrice: 120000,
    currentPrice: 140000,
    minimumIncrement: 5000,
    startTime: new Date(),
    endTime: new Date(Date.now() + 86400000 * 2),
    imageUrls: ["https://images.unsplash.com/photo-1597045566677-8cf032ed6634?w=800"],
  },
  {
    title: "Nike MAG 'Back to the Future' 2016",
    description: "Sepatu impian para sneakerhead sejati dengan sistem auto-lacing.",
    category: "Sneaker Hype & Streetwear",
    rarity: "LEGENDARY",
    auctionType: "STANDARD",
    status: "ACTIVE",
    startingPrice: 600000,
    currentPrice: 650000,
    minimumIncrement: 20000,
    startTime: new Date(),
    endTime: new Date(Date.now() + 86400000 * 3),
    imageUrls: ["https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800"],
  },

  // Tas Desainer & Fashion Elite
  {
    title: "Hermes Birkin 30 Crocodile Diamond",
    description: "Tas Hermes Birkin paling dicari. Berlian murni pada perangkat kerasnya.",
    category: "Tas Desainer & Fashion Elite",
    rarity: "LEGENDARY",
    auctionType: "STANDARD",
    status: "ACTIVE",
    startingPrice: 1800000,
    currentPrice: 1800000,
    minimumIncrement: 50000,
    startTime: new Date(),
    endTime: new Date(Date.now() + 86400000 * 4),
    imageUrls: ["https://images.unsplash.com/photo-1584916201218-f4242ceb4809?w=800"],
  },
  {
    title: "Louis Vuitton Trunk Vintage (Koper)",
    description: "Koper bagasi LV orisinal dari awal tahun 1900-an. Membawa sejarah era awal travel mewah.",
    category: "Tas Desainer & Fashion Elite",
    rarity: "EPIC",
    auctionType: "STANDARD",
    status: "ACTIVE",
    startingPrice: 150000,
    currentPrice: 165000,
    minimumIncrement: 5000,
    startTime: new Date(),
    endTime: new Date(Date.now() + 86400000 * 6),
    imageUrls: ["https://images.unsplash.com/photo-1547949007-56b73ebc2084?w=800"],
  }
];

async function main() {
  console.log("Seeding realistic auctions...");
  let count = 0;
  for (const item of realisticAuctions) {
    await prisma.auction.create({
      data: item
    });
    count++;
  }
  console.log(`Berhasil menambahkan ${count} item lelang realistis ke database!`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
